/turtlebot1/controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [simple]
    simple:
      rt_freq: 30.0
      plugin: easynav_simple_controller/SimpleController
      max_linear_speed: 0.6
      max_angular_speed: 1.0
      look_ahead_dist: 0.2
      k_rot: 0.5

/turtlebot1/localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [simple]
    simple:
      rt_freq: 50.0
      freq: 5.0
      reseed_freq: 1.0
      plugin: easynav_simple_localizer/AMCLLocalizer
      num_particles: 100
      noise_translation: 0.05
      noise_rotation: 0.1
      noise_translation_to_rotation: 0.1
      initial_pose:
        x: 32.35839943118211
        y: -14.000218110974842
        yaw: 1.52
        std_dev_xy: 0.1
        std_dev_yaw: 0.01

/turtlebot1/maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [simple]
    simple:
      freq: 10.0
      plugin: easynav_simple_maps_manager/SimpleMapsManager
      package: my_world
      map_path_file: maps/my_world/easynav_my_world.map

/turtlebot1/planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [simple]
    simple:
      freq: 0.5
      plugin: easynav_simple_planner/SimplePlanner
      robot_radius: 0.3

/turtlebot1/sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1:
      topic: scan_easynav
      type: sensor_msgs/msg/LaserScan

/turtlebot1/system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    use_cmd_vel_stamped: true
    position_tolerance: 0.1
    angle_tolerance: 0.06
    map_frame: map
    odom_frame: turtlebot1/odom
    robot_frame: turtlebot1/base_link
    world_frame: map
    tf_prefix: ""
