# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "turtlebot2"
  limits:
    linear: [0.31, 0.75]
    angular: [1.90, 2.0]

  profile:
    footprint: 0.22
    vicinity: 0.50

  reversible: True

  battery_system:
    voltage: 14.4
    capacity: 5.0
    charging_current: 2.0

  mechanical_system:
    mass: 3.5
    moment_of_inertia: 1.0
    friction_coefficient: 0.22

  ambient_system:
    power: 5.0

  tool_system:
    power: 0.0

  recharge_threshold: 0.10
  recharge_soc: 1.0

  publish_fleet_state: 10.0
  account_for_battery_drain: False

  task_capabilities:
    loop: True
    delivery: False

  actions: []

  finishing_request: "park"
  responsive_wait: True

  robots:
    turtlebot2:
      charger: "turtlebot2_charger"
      responsive_wait: False

  robot_state_update_frequency: 10.0


fleet_manager:
  prefix: "http://127.0.0.1:8080"
  user: "some_user"
  password: "some_password"
  namespace: "turtlebot2"
  navigation_backend: nav2
  initial_pose_source: "world_charger"
  initial_pose_world_package: "my_world"
  initial_pose_world_name: "my_world"
  initial_pose_yaw: 1.52
  initial_pose_frame: "map"
  initial_pose_retry_period: 2.0


# TRANSFORM CONFIG =============================================================

navigation_backend: nav2

reference_coordinates:
  L1:
    rmf:
      - [46.749, -3.719]    # turtlebot2_charger
      - [2.473, -6.965]     # room5_2
      - [8.965, -7.072]     # hall_1
      - [21.099, -3.400]    # room1_1
    robot:
      - [46.749, -3.719]    # turtlebot2_charger
      - [2.473, -6.965]     # room5_2
      - [8.965, -7.072]     # hall_1
      - [21.099, -3.400]    # room1_1
